#FROM nvcr.io/nvidia/l4t-tensorrt:r8.5.2-runtime
FROM nvcr.io/nvidia/l4t-cuda:10.2.460-runtime

WORKDIR /workspace

RUN wget -q -O - https://repo.download.nvidia.com/jetson/jetson-ota-public.asc | apt-key add - && \
  echo "deb https://repo.download.nvidia.com/jetson/common r32.7 main" > /etc/apt/sources.list.d/nvidia-l4t-apt-source.list && \
  echo "deb https://repo.download.nvidia.com/jetson/t194 r32.7 main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list


ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-opencv \
    python3-numpy \
    python3-pil \
    && apt-get clean

ARG DEBIAN_FRONTEND=noninteractive
#RUN apt-get install -y cuda
RUN apt-get install -y tensorrt
RUN apt-get install -y nvidia-container-toolkit
# apt-get install -y libnvinfer8 libnvinfer-dev libnvinfer-plugin8


# Copy the model and script into the container
COPY test.engine /workspace/test.engine
COPY lane_test.py /workspace/lane_test.py
COPY images /workspace/images

# Install the required Python packages

RUN pip3 install numpy opencv-python Pillow tensorrt pycuda

# Set the command to run the Python script
#CMD ["python3", "lane_test.py"]

